# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d36becd50884c7cc21ee77f9650c90a"
name = "dynamic-processing"
handle = "dynamic-processing"
application_url = "https://542f-2601-249-8d01-e50-fd9d-a78e-fcfe-626b.ngrok-free.app"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "pollenlabs.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://542f-2601-249-8d01-e50-fd9d-a78e-fcfe-626b.ngrok-free.app/auth/callback",
  "https://542f-2601-249-8d01-e50-fd9d-a78e-fcfe-626b.ngrok-free.app/auth/shopify/callback",
  "https://542f-2601-249-8d01-e50-fd9d-a78e-fcfe-626b.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
