name = "remix"
roles = ["frontend", "backend"]
webhooks_path = "/app/routes/webhooks"
port=3000

[commands]
predev = "npx prisma generate"
dev = "npx prisma migrate deploy && npm exec remix vite:dev"
