# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "1d36becd50884c7cc21ee77f9650c90a"
name = "dynamic-processing"
handle = "dynamic-processing"
application_url = "https://02f5-2600-1700-5523-831f-80c1-db83-5b82-f503.ngrok-free.app/"
embedded = true

[build]
automatically_update_urls_on_dev = false
dev_store_url = "pollenlabs.myshopify.com"
include_config_on_deploy = true

[access.admin]
direct_api_mode = "online"
embedded_app_direct_api_access = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://02f5-2600-1700-5523-831f-80c1-db83-5b82-f503.ngrok-free.app/auth/callback",
  "https://02f5-2600-1700-5523-831f-80c1-db83-5b82-f503.ngrok-free.app/auth/shopify/callback",
  "https://02f5-2600-1700-5523-831f-80c1-db83-5b82-f503.ngrok-free.app/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

  [[webhooks.subscriptions]]
  topics = [
  "app/uninstalled",
  "orders/cancelled",
  "orders/create",
  "orders/fulfilled"
]
  uri = "https://090b-2601-249-8d01-e50-aa7-570e-86f6-2059.ngrok-free.app/webhooks"

[pos]
embedded = false
